### ISSUE TITLE
How to send Data from ViewModel to Model ( e.g start Animation ) 

### ISSUE THREAD

**Issue by FriedrichWessel** [NVentimiglia/Unity3d-Databinding-Mvvm-Mvc#10]
Hello, 

I tested this framework this weekend, and it works great  for the following cases: 
- Data ( like text, image, list content ) get changed in the VM -> View can be binded and udpated
- View Provides Input -> VM Function get called

What I miss is the possibility to bind something other than plain data. For example I want to disable a button and play his disable animation. Or I need to change the position of a button because some new options are availabe after some Input. 

Is there an option for this kind of bindign already or do I have to create my own bind classes ? 

Thanks for your help!

Friedrich

**Comment by NVentimiglia** [comment]
Disabling a button can be done via binding the Enabled value to a bool. But your right, perhaps better integration with animation is something that is needed.

For creating your own inherit from BindingBase. Lets take a look at the ButtonBinder. I have added better comments in the latest push.

[Button Binder](https://github.com/NVentimiglia/Unity3d-Databinding-Mvvm-Mvc/blob/master/Foundation%20Databinding/Assets/Foundation/Databinding/Components/ButtonBinder.cs)

So your TLDR is :
- Inhert from BinderBase
- Add BindingInfo fields
- Listen To BindingField.Action for Model --> View
- SetVale for View --> Model

From the sounds of your issue you need two binders.

[Transform Binder](https://github.com/NVentimiglia/Unity3d-Databinding-Mvvm-Mvc/blob/master/Foundation%20Databinding/Assets/Foundation/Databinding/Components/TransformBinder.cs)

[AnimationBinder](https://github.com/NVentimiglia/Unity3d-Databinding-Mvvm-Mvc/blob/master/Foundation%20Databinding/Assets/Foundation/Databinding/Components/AnimationBinder.cs)

This should point you in the right direction. I will leave this issue open for now.
