### ISSUE TITLE
ListBinder Awake runs in edit mode

### ISSUE THREAD

**Issue by MatthewDrotar** [NVentimiglia/Unity3d-Databinding-Mvvm-Mvc#12]
This causes a few issues, especially when using an actual prefab for the list item (warns of data corruption).

I wrapped the contents of the ListBinder.Awake() method with 
if (Application.isPlaying) { ... }
and it seemed to avoid those issues.

**Comment by NVentimiglia** [comment]
Thanks, I will take a look at this issue tuesday.

**Comment by NVentimiglia** [comment]
#6379908
