### ISSUE TITLE
Status of Unity5 Functionality

### ISSUE THREAD

**Issue by negue** [NVentimiglia/Unity3d-Databinding-Mvvm-Mvc#2]
Is there any status page of what works in Unity5 and what not?

Anyway I tried the Observabletests Scene, it compiles without errors, once I try something it rains tons of errors :D (in the Console)

Also the selection of the "ViewModel Component" seems not to work, I can't select any file / class

**Comment by NVentimiglia** [comment]
What are the errors and on what platform? I am using Unity5 right now.

**Comment by negue** [comment]
Is there an easy way to get all log messages ? One at a time is bit much to copy & paste :D

**Comment by NVentimiglia** [comment]
http://docs.unity3d.com/Manual/LogFiles.html

**Comment by negue** [comment]
Thanks! (still a unity / game dev noob) 

https://gist.github.com/negue/394aa37ecee2a7f985f1

**Comment by negue** [comment]
FYI I imported all packages from your git repos (but before I had the 3.2 Version imported, should I remove and re-import everything) ?

**Comment by NVentimiglia** [comment]
Yeah, I would recommend deleting the old stuff and re-importing. There were a number of API changes which will cause headaches if you try to convert. It took me the better part of the weekend to upgrade the lobby for Unity5 / Foundation4 for instance.

The lobby and server also had a moderate upgrade as well (those are pending in the asset store). I have the new server and lobby temporarily here : http://mmofoundation.com.petunia.arvixe.com/Wiki

**Comment by negue** [comment]
Removed all, and reimported all packages again. 

The new databinding scene shows me no controls and once I try to run it, I get these errors:

https://gist.github.com/negue/8015501415c3ede3fbd8

**Comment by negue** [comment]
This is also strange, a screenshot of LocalizationService.asset http://i.imgur.com/jZgHTBm.png

**Comment by NVentimiglia** [comment]
What platform ? I just tested on a new project and built for Windows and Web.

**Comment by NVentimiglia** [comment]
Ok, looks like something is getting corrupted on the import.

Try this.

1) Redownload this git

2) Create a new unity project

3) Import the .unityPackage (file in root of git)

4) add NoLocalization (or import that also)

5) run.

**Comment by negue** [comment]
Windows 8.1 x64
Unity 5.0.0f4

Okay I`ll try that

to 3) I didn't even know that it is possible to import the package not in the root folder

**Comment by NVentimiglia** [comment]
I meant its in the root of the git

**Comment by negue** [comment]
Huh, it works with a clean project. Seems that there is something wrong with my current project?

Thanks for the live support :P

I`ll test tomorrow again with my normal project and see If I can get it to run there too, will update once I have some new informations

**Comment by NVentimiglia** [comment]
Np =)

Hopefully resetting the primary power coupling might help.
