### ISSUE TITLE
ListBinder only working in Editor

### ISSUE THREAD

**Issue by negue** [NVentimiglia/Unity3d-Databinding-Mvvm-Mvc#6]
If I try to use a ListBinder it only works in the Editor, on each export (Windows, Android or WSA) it doesn't work:
- no items are created
- also no errors are in the log

**Comment by NVentimiglia** [comment]
I think the problem is on your end. I use the list binder daily and just double checked the example.

Can you show me your model's code and a screenshot of your inspector ?

**Comment by negue** [comment]
I tried to debug in the C# WSA Project, all ListBinder lines are getting called, so atleast this is not the problem.

I also tried to have simple script without any binding stuff, and this code worked too ...:

``` c#
 var next = Instantiate(Prefab, transform.position, transform.rotation) as GameObject;
      next.transform.SetParent(this.transform);

      next.transform.localScale = Prefab.transform.localScale;
      next.SetActive(true);
```

My ViewModel / Model Code:

``` c#
using Foundation.Databinding.Model;
using UnityEngine;

public class TestItemViewModel : ObservableObject
{
   public string Test { get; set; }
}

public class TestViewModel : MonoBehaviour {

   public ObservableCollection<TestItemViewModel> Items = new ObservableCollection<TestItemViewModel>();

   public void Awake()
   {
      Items.Add(new TestItemViewModel
      {
         Test = "1"
      });
      Items.Add(new TestItemViewModel
      {
         Test = "12"
      });
   }
}


```

Inspector Screenshots:
![2015-03-31_19-30-50](https://cloud.githubusercontent.com/assets/842273/6925038/16109454-d7dd-11e4-9366-d3bc2b837baa.png)
![2015-03-31_19-31-21](https://cloud.githubusercontent.com/assets/842273/6925039/1619d3a2-d7dd-11e4-92fc-f2b10ad89f6c.png)
![2015-03-31_19-31-54](https://cloud.githubusercontent.com/assets/842273/6925040/161bbb22-d7dd-11e4-8047-841043115a8e.png)

**Comment by NVentimiglia** [comment]
From what I see., everything should work.  I am unable to replicate the error on my end. 

Can you upload the example somewhere ?

**Comment by negue** [comment]
Now I kinda managed to brake everything -.- no items even in the editor man thats strange ...

Anyway I'll close this for now and if I have everything running again I may re open this issue.

**Comment by NVentimiglia** [comment]
Best of luck. If you manage to upload a simple example of the error, Ill take a look.
