### ISSUE TITLE
ListBinder & Scaling

### ISSUE THREAD

**Issue by negue** [NVentimiglia/Unity3d-Databinding-Mvvm-Mvc#7]
I don't know why the Databinding Example 1 works, but if I copy & paste the example everything works except one thing. Each ListBinder Item gets the Scale of {0,0,0}

I had to change it to:

``` c#
next.transform.localScale = new Vector3(1,1,1);
```

Sure some may need a different scale, so why not create a property where it is possible to change it to the desired scale?

**Comment by NVentimiglia** [comment]
Yeah, that was a really weird that the scale gets corrupted. My fix works but it is hackish.

I will either expose the property for the next release or find a better way of fixing the error.

**Comment by NVentimiglia** [comment]
Updated in de5e223. I use the templates scale now.
