### ISSUE TITLE
Support for INotifyPropertyChanged

### ISSUE THREAD

**Issue by MatthewDrotar** [NVentimiglia/Unity3d-Databinding-Mvvm-Mvc#8]
I understand that IObservableModel is supposed to replace INotifyPropertyChanged in the library, but please consider supporting change notifications from INotifyPropertyChanged objects in addition to IObservableModel objects.

I need to bind to class types that already inherit from a base class. INotifyPropertyChanged is well-known, portable and less cumbersome to implement. Implementing INotifyPropertyChanged requires one event compared to IObservableModel which is would require some stateful backend code. And multiply that by each class that needs to support binding.

If this is not something you think should be supported, could you provide some hints as to how I might implement it on my own?

**Comment by NVentimiglia** [comment]
That is something I will support in the future.

The key will to augment the modelbinder class to support IPropertyNotifyChanged. 
https://github.com/NVentimiglia/Unity3d-Databinding-Mvvm-Mvc/blob/master/Foundation.Databinding.Model/Foundation.Databinding.Model/ModelBinder.cs

**Comment by NVentimiglia** [comment]
Added in de5e223. You may now write your model dependency free,

One note is the ObservableCollection class I use is not standard either as it does not exist in unity. You will need to write your own shared collection to use in your model library.

**Comment by MatthewDrotar** [comment]
Thanks!
